---
- name: My Super Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Hello from IT"

  tasks:
  - name: Ping test
    ping:

   
  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml
